Corrección para evitar error por variable no usada
Al hacer make no finalizaba exitosamente la compilación por tomar el warning como error "cc1: all warnings being treated as errors"
Añadido el flag -Wno-unused-variable para evitar esto: 

../py/objenumerate.c:42:23: error: 'enumerate_make_new_args' defined but not used [-Werror=unused-const-variable=]
 STATIC const mp_arg_t enumerate_make_new_args[] = {
                       ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [../py/mkrules.mk:47: build/py/objenumerate.o] Error 1